[package]
name = "devil_apartment"
version = "0.1.0"
authors = ["Nalleyer <nalleyer@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.3"
rayon = "1.5.1"

[lib]
crate-type = ["cdylib"]